---
EPTRN_HASH:
  DATA_FILE_HEADER_RECORD:
    DF_HDR_RECORD_TYPE: 0_4
    DF_HDR_DATE: 5_12
    DF_HDR_TIME: 13_16
    DF_HDR_FILE_ID: 17_22
    DF_HDR_FILE_NAME: 23_42
  TRANSACTION:
    SUMMARY_RECORD:
      AMEX_PAYEE_NUMBER: 0_9
      AMEX_SORT_FIELD_1: 10_19
      AMEX_SORT_FIELD_2: 20_29
      PAYMENT_YEAR: 30_33
      PAYMENT_NUMBER: 34_41
      RECORD_TYPE: 42_42
      DETAIL_RECORD_TYPE: 43_44
      PAYMENT_DATE: 45_51
      PAYMENT_AMOUNT: 52_62
      DEBIT_BALANCE_AMOUNT: 63_71
      ABA_BANK_NUMBER: 72_80
      SE_DDA_NUMBER: 81_97
    SUMMARY_OF_CHARGE_DETAIL_RECORD:
      AMEX_PAYEE_NUMBER: 0_9
      AMEX_SE_NUMBER: 10_19
      SE_UNIT_NUMBER: 20_29
      PAYMENT_YEAR: 30_33
      PAYMENT_NUMBER: 34_41
      RECORD_TYPE: 42_42
      DETAIL_RECORD_TYPE: 43_44
      SE_BUSINESS_DATE: 45_51
      AMEX_PROCESS_DATE: 52_58
      SOC_INVOICE_NUMBER: 59_64
      SOC_AMOUNT: 65_75
      DISCOUNT_AMOUNT: 76_84
      SERVICE_FEE_AMOUNT: 85_91
      NET_SOC_AMOUNT: 99_109
      DISCOUNT_RATE: 110_114
      SERVICE_FEE_RATE: 115_119
      AMEX_GROSS_AMOUNT: 141_151
      AMEX_ROC_COUNT: 152_156
      TRACKING_ID: 157_165
      CPC_INDICATOR: 166_166
      AMEX_RO_COUNT_POA: 182_188
    RECORD_OF_CHARGE_DETAIL_RECORD:
      TLRR_AMEX_PAYEE_NUMBER: 0_9
      TLRR_AMEX_SE_NUMBER: 10_19
      TLRR_SE_UNIT_NUMBER: 20_29
      TLRR_PAYMENT_YEAR: 30_33
      TLRR_PAYMENT_NUMBER: 34_41
      TLRR_RECORD_TYPE: 42_42
      TLRR_DETAIL_RECORD_TYPE: 43_44
      TLRR_SE_BUSINESS_DATE: 45_51
      TLRR_AMEX_PROCESS_DATE: 52_58
      TLRR_SOC_INVOICE_NUMBER: 59_64
      TLRR_SOC_AMOUNT: 65_77
      TLRR_ROC_AMOUNT: 78_90
      TLRR_CM_NUMBER: 91_105
      TLRR_CM_REF_NO: 106_116
      TLRR_SE_REF: 117_125
      TLRR_SE_REF_EXPANSION_FILLER: 126_135
      TLRR_ROC_NUMBER: 136_145
      TLRR_TRAN_DATE: 146_152
      TLRR_SE_REF_POA: 153_182
      NON_COMPLIANT_INDICATOR: 183_183
      NON_COMPLIANT_ERROR_CODE_1: 184_187
      NON_COMPLIANT_ERROR_CODE_2: 188_191
      NON_COMPLIANT_ERROR_CODE_3: 192_185
      NON_COMPLIANT_ERROR_CODE_4: 196_199
      NON_SWIPED_INDICATOR: 200_200
    CHARGEBACK_DETAIL_RECORD:
      AMEX_PAYEE_NUMBER: 0_9
      AMEX_SE_NUMBER: 10_19
      SE_UNIT_NUMBER: 20_29
      PAYMENT_YEAR: 30_33
      PAYMENT_NUMBER: 34_41
      RECORD_TYPE: 42_42
      DETAIL_RECORD_TYPE: 43_44
      SE_BUSINESS_DATE: 45_51
      AMEX_PROCESS_DATE: 52_58
      SOC_INVOICE_NUMBER: 59_64
      SOC_AMOUNT: 65_75
      CHARGEBACK_AMOUNT: 76_84
      DISCOUNT_AMOUNT: 85_93
      SERVICE_FEE_AMOUNT: 94_100
      NET_CHARGEBACK_AMOUNT: 108_116
      DISCOUNT_RATE: 117_121
      SERVICE_FEE_RATE: 122_126
      CHARGEBACK_REASON: 143_422
    ADJUSTMENT_DETAIL_RECORD:
      AMEX_PAYEE_NUMBER: 0_9
      AMEX_SE_NUMBER: 10_19
      SE_UNIT_NUMBER: 20_29
      PAYMENT_YEAR: 30_33
      PAYMENT_NUMBER: 34_41
      RECORD_TYPE: 42_42
      DETAIL_RECORD_TYPE: 43_44
      AMEX_PROCESS_DATE: 45_51
      ADJUSTMENT_NUMBER: 52_57
      ADJUSTMENT_AMOUNT: 58_66
      DISCOUNT_AMOUNT: 67_75
      SERVICE_FEE_AMOUNT: 76_82
      NET_ADJUSTMENT_AMOUNT: 90_98
      DISCOUNT_RATE: 99_103
      SERVICE_FEE_RATE: 104_108
      CARDMEMBER_NUMBER: 125_141
      ADJUSTMENT_REASON: 142_421
    OTHER_FEES_AND_REVENUES_DETAIL_RECORDS:
      AMEX_PAYEE_NUMBER: 0_9
      AMEX_SE_NUMBER: 10_19
      SE_UNIT_NUMBER: 20_29
      PAYMENT_YEAR: 30_33
      PAYMENT_NUMBER: 34_41
      RECORD_TYPE: 42_42
      DETAIL_RECORD_TYPE: 43_44
      AMEX_PROCESS_DATE: 45_51
      ASSET_BILLING_AMOUNT: 52_60
      ASSET_BILLING_DESCRIPTION: 61_126
      TAKE_ONE_COMMISSION_AMOUNT: 126_135
      TAKE_ONE_DESCRIPTION: 135_214
      OTHER_FEE_AMOUNT: 215_223
      OTHER_FEE_DESCRIPTION: 224_303
      ASSET_BILLING_TAX: 304_312
  DATA_FILE_TRAILER_RECORD:
    DF_TRL_RECORD_TYPE: 0_4
    DF_TRL_DATE: 5_12
    DF_TRL_TIME: 13_16
    DF_TRL_FILE_ID: 17_22
    DF_TRL_FILE_NAME: 23_42
    DF_TRL_RECIPIENT_KEY: 43_82
    DF_TRL_RECORD_COUNT: 83_89
