DATA_FILE_HEADER_RECORD:
  FIELDS:
    DF_HDR_RECORD_TYPE: [0, 4]
    DF_HDR_DATE: [5, 12]
    DF_HDR_TIME: [13, 16]
    DF_HDR_FILE_ID: [17, 22]
    DF_HDR_FILE_NAME: [23, 42]
DETAIL_RECORD:
  ABSTRACT: true
  RECURRING: true
  TYPE_FIELD: [43, 44]
  TYPE_MAPPING:
    '00': SUMMARY_RECORD
    '10': SUMMARY_OF_CHARGE_DETAIL_RECORD
    '11': RECORD_OF_CHARGE_DETAIL_RECORD
    '20': CHARGEBACK_DETAIL_RECORD
    '30': ADJUSTMENT_DETAIL_RECORD
    '50': OTHER_FEES_AND_REVENUES_DETAIL_RECORDS
  TYPES:
    SUMMARY_RECORD:
      RECURRING: true
      FIELDS:
        AMEX_PAYEE_NUMBER: [0, 9]
        AMEX_SORT_FIELD_1: [10, 19]
        AMEX_SORT_FIELD_2: [20, 29]
        PAYMENT_YEAR: [30, 33]
        PAYMENT_NUMBER: [34, 41]
        RECORD_TYPE: [42, 42]
        DETAIL_RECORD_TYPE: [43, 44]
        PAYMENT_DATE: [45, 51]
        PAYMENT_AMOUNT: [52, 62]
        DEBIT_BALANCE_AMOUNT: [63, 71]
        ABA_BANK_NUMBER: [72, 80]
        SE_DDA_NUMBER: [81, 97]
    SUMMARY_OF_CHARGE_DETAIL_RECORD:
      RECURRING: true
      FIELDS:
        AMEX_PAYEE_NUMBER: [0, 9]
        AMEX_SE_NUMBER: [10, 19]
        SE_UNIT_NUMBER: [20, 29]
        PAYMENT_YEAR: [30, 33]
        PAYMENT_NUMBER: [34, 41]
        RECORD_TYPE: [42, 42]
        DETAIL_RECORD_TYPE: [43, 44]
        SE_BUSINESS_DATE: [45, 51]
        AMEX_PROCESS_DATE: [52, 58]
        SOC_INVOICE_NUMBER: [59, 64]
        SOC_AMOUNT: [65, 75]
        DISCOUNT_AMOUNT: [76, 84]
        SERVICE_FEE_AMOUNT: [85, 91]
        NET_SOC_AMOUNT: [99, 109]
        DISCOUNT_RATE: [110, 114]
        SERVICE_FEE_RATE: [115, 119]
        AMEX_GROSS_AMOUNT: [141, 151]
        AMEX_ROC_COUNT: [152, 156]
        TRACKING_ID: [157, 165]
        CPC_INDICATOR: [166, 166]
        AMEX_RO_COUNT_POA: [182, 188]
    RECORD_OF_CHARGE_DETAIL_RECORD:
      RECURRING: true
      FIELDS:
        TLRR_AMEX_PAYEE_NUMBER: [0, 9]
        TLRR_AMEX_SE_NUMBER: [10, 19]
        TLRR_SE_UNIT_NUMBER: [20, 29]
        TLRR_PAYMENT_YEAR: [30, 33]
        TLRR_PAYMENT_NUMBER: [34, 41]
        TLRR_RECORD_TYPE: [42, 42]
        TLRR_DETAIL_RECORD_TYPE: [43, 44]
        TLRR_SE_BUSINESS_DATE: [45, 51]
        TLRR_AMEX_PROCESS_DATE: [52, 58]
        TLRR_SOC_INVOICE_NUMBER: [59, 64]
        TLRR_SOC_AMOUNT: [65, 77]
        TLRR_ROC_AMOUNT: [78, 90]
        TLRR_CM_NUMBER: [91, 105]
        TLRR_CM_REF_NO: [106, 116]
        TLRR_SE_REF: [117, 125]
        TLRR_SE_REF_EXPANSION_FILLER: [126, 135]
        TLRR_ROC_NUMBER: [136, 145]
        TLRR_TRAN_DATE: [146, 152]
        TLRR_SE_REF_POA: [153, 182]
        NON_COMPLIANT_INDICATOR: [183, 183]
        NON_COMPLIANT_ERROR_CODE_1: [184, 187]
        NON_COMPLIANT_ERROR_CODE_2: [188, 191]
        NON_COMPLIANT_ERROR_CODE_3: [192, 195]
        NON_COMPLIANT_ERROR_CODE_4: [196, 199]
        NON_SWIPED_INDICATOR: [200, 200]
    CHARGEBACK_DETAIL_RECORD:
      RECURRING: true
      FIELDS:
        AMEX_PAYEE_NUMBER: [0, 9]
        AMEX_SE_NUMBER: [10, 19]
        SE_UNIT_NUMBER: [20, 29]
        PAYMENT_YEAR: [30, 33]
        PAYMENT_NUMBER: [34, 41]
        RECORD_TYPE: [42, 42]
        DETAIL_RECORD_TYPE: [43, 44]
        SE_BUSINESS_DATE: [45, 51]
        AMEX_PROCESS_DATE: [52, 58]
        SOC_INVOICE_NUMBER: [59, 64]
        SOC_AMOUNT: [65, 75]
        CHARGEBACK_AMOUNT: [76, 84]
        DISCOUNT_AMOUNT: [85, 93]
        SERVICE_FEE_AMOUNT: [94, 100]
        NET_CHARGEBACK_AMOUNT: [108, 116]
        DISCOUNT_RATE: [117, 121]
        SERVICE_FEE_RATE: [122, 126]
        CHARGEBACK_REASON: [143, 422]
    ADJUSTMENT_DETAIL_RECORD:
      RECURRING: true
      FIELDS:
        AMEX_PAYEE_NUMBER: [0, 9]
        AMEX_SE_NUMBER: [10, 19]
        SE_UNIT_NUMBER: [20, 29]
        PAYMENT_YEAR: [30, 33]
        PAYMENT_NUMBER: [34, 41]
        RECORD_TYPE: [42, 42]
        DETAIL_RECORD_TYPE: [43, 44]
        AMEX_PROCESS_DATE: [45, 51]
        ADJUSTMENT_NUMBER: [52, 57]
        ADJUSTMENT_AMOUNT: [58, 66]
        DISCOUNT_AMOUNT: [67, 75]
        SERVICE_FEE_AMOUNT: [76, 82]
        NET_ADJUSTMENT_AMOUNT: [90, 98]
        DISCOUNT_RATE: [99, 103]
        SERVICE_FEE_RATE: [104, 108]
        CARDMEMBER_NUMBER: [125, 141]
        ADJUSTMENT_REASON: [142, 421]
    OTHER_FEES_AND_REVENUES_DETAIL_RECORDS:
      RECURRING: true
      FIELDS:
        AMEX_PAYEE_NUMBER: [0, 9]
        AMEX_SE_NUMBER: [10, 19]
        SE_UNIT_NUMBER: [20, 29]
        PAYMENT_YEAR: [30, 33]
        PAYMENT_NUMBER: [34, 41]
        RECORD_TYPE: [42, 42]
        DETAIL_RECORD_TYPE: [43, 44]
        AMEX_PROCESS_DATE: [45, 51]
        ASSET_BILLING_AMOUNT: [52, 60]
        ASSET_BILLING_DESCRIPTION: [61, 126]
        TAKE_ONE_COMMISSION_AMOUNT: [126, 134]
        TAKE_ONE_DESCRIPTION: [135, 214]
        OTHER_FEE_AMOUNT: [215, 223]
        OTHER_FEE_DESCRIPTION: [224, 303]
        ASSET_BILLING_TAX: [304, 312]
DATA_FILE_TRAILER_RECORD:
  TRAILER: true
  FIELDS:
    DF_TRL_RECORD_TYPE: [0, 4]
    DF_TRL_DATE: [5, 12]
    DF_TRL_TIME: [13, 16]
    DF_TRL_FILE_ID: [17, 22]
    DF_TRL_FILE_NAME: [23, 42]
    DF_TRL_RECIPIENT_KEY: [43, 82]
    DF_TRL_RECORD_COUNT: [83, 89]
